name: CI/CD Microservices & AWS QA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Nx Workspace Lint
        run: npx nx run-many -t lint

      # 1. Build de los servicios
      - name: Build Servicios
        run: |
          npx nx run-many -t build --projects=user-service,report-service,audit-service,deposit-service,health-service,iot-gateway,notification-service,reward-service,api-gateway,web-dashboard
          
      - name: Build Auth Service (Especial)
        run: |
          export NODE_OPTIONS="--no-warnings"
          npx nx build auth-service

      # 2. Infraestructura con Terraform
      #- name: Setup Terraform
      #  uses: hashicorp/setup-terraform@v2

      #- name: Terraform Deploy (QA)
       # working-directory: ./terraform 
        #run: |
         # terraform init
          #terraform apply -auto-approve
        #env:
        #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          #AWS_REGION: us-east-1

      # 3. --- NUEVO: SUBIR A DOCKER ECR ---
      - name: Configure AWS credentials for Docker
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.registry }}
          ECR_REPOSITORY: uce-proyecto-repo
          IMAGE_TAG: latest
        run: |
          # Construimos la imagen usando el Dockerfile de la raíz
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Subimos al repositorio
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG