name: CI Microservices Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-all-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

        # Verificar que todo el workspace está correcto
      - name: Nx Workspace Lint
        run: npx nx run-many -t lint

      # Ejecuta los 10 microservicios
      - name: Build Servicios Estándar
        run: |
          npx nx run-many -t build --projects=user-service,report-service,audit-service,deposit-service,health-service,iot-gateway,notification-service,reward-service,api-gateway,web-dashboard

      # Ejecuta el auth service de manera especial
      - name: Build Auth Service (Configuración Especial)
        run: npx nx build auth-service
        env:
          NODE_OPTIONS: "--no-warnings"

      # Configuración Infraestructura con Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan & Apply
        run: |
          terraform plan
          # Si quieres que se cree en AWS automáticamente, usa: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: "us-east-1"
